### PR TITLE
Testing

### PR DESCRIPTION
**Pull request by ericgaspar**

### CODE REVIEW

**Comment by ericgaspar** [comment]
!testme

**Comment by ericgaspar** [comment]
!testme

**Comment by rndmh3ro** [comment]
You should remove the [.DS_Store](https://github.com/YunoHost-Apps/libreddit_ynh/pull/1/files#diff-e2eb93a61ffd7877ea5c751abcb3a618e8e2e9a2073a27f66d4114fe10819f86) file

**Comment by ericgaspar** [comment]
yep, thanks!

**Pull request merged**
