### PR TITLE
Update to new 0.30.1 binary

### PR DESCRIPTION
**Pull request by sigaloid**
## Problem

- Newer version with new shasum

## Solution

- Use new shasum and binary URL

## PR Status

- [x] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable) (I do not run yunohost, cannot test)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by sigaloid** [comment]
Fixes #41

**Comment by ericgaspar** [comment]
!testme

**Comment by ericgaspar** [comment]
Thanks for looking after the issue!

We have this error during install validation tests

```
Fatal glibc error: dl-call-libc-early-init.c:37 (_dl_call_libc_early_init): assertion failed: sym != NULL
```

https://ci-apps-dev.yunohost.org/ci/job/7652

**Comment by sigaloid** [comment]
Urgh I worried about this happening - static compiling is a pain. Is there a way to test running the binary the same way YunoHost will do? I thought a debian:bullseye container would be enough to test it on, but I guess not. Is there a standard version of Debian it will run it on?

**Comment by ericgaspar** [comment]
closing with #53

**Pull request closed without merging**
