### PR TITLE
feat(config): add config panel

### PR DESCRIPTION
**Pull request by rndmh3ro**
## Problem

No way to configure redlibs settings per instance

## Solution

Add a config panel

## PR Status

- [x] Code finished and ready to be reviewed/tested
- [x] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by rndmh3ro** [comment]
!testme

**Comment by rndmh3ro** [comment]
@ericgaspar, can you take a look? I'm not able to merge in this repo.

**Comment by ericgaspar** [comment]
did you get it to work?

**Comment by rndmh3ro** [comment]
Screenshot_20241001-190529

Yes, works great!

**Pull request merged**
